// Mission definitions: spawn, loadout, sequential objectives.
// Desert Strike is fully playable in Phase A; arctic/urban unlock in Phase B.
export const MISSIONS = {
  desert: {
    id: 'desert',
    name: 'DESERT STRIKE',
    desc: 'Fight through a desert town at sunset and destroy the enemy communications post.',
    difficulty: 'Medium',
    playable: true,
    weapons: ['AR7', 'KX9'],
    spawn: [0, 0.2, 46],
    spawnYaw: Math.PI, // facing -z into town
    ammoCrates: [[3, 0, 42], [-8, 0, 10], [7, 0, -50]],
    objectives: [
      { id: 'enter', title: 'Enter the town', desc: 'Advance through the south gate', target: [0, 32] },
      { id: 'patrol', title: 'Eliminate the patrol', desc: 'Clear hostiles near the entrance', target: 'enemies' },
      { id: 'market', title: 'Cross the market', desc: 'Push through the abandoned market', target: [0, 0] },
      { id: 'roofs', title: 'Clear the rooftops', desc: 'Eliminate rooftop hostiles', target: 'enemies' },
      { id: 'plaza', title: 'Reach the plaza', desc: 'Advance to the central plaza', target: [0, -26] },
      { id: 'vehicle', title: 'Destroy the gun truck', desc: 'Blow up the armed vehicle', target: [6, -32] },
      { id: 'comms', title: 'Reach the comms center', desc: 'Get to the communications building', target: [0, -58] },
      { id: 'plant', title: 'Plant the explosive', desc: 'Press F at the comms relay', target: [0, -61] },
      { id: 'escape', title: 'Escape the blast', desc: 'Get clear before detonation', target: [0, 46] },
    ],
  },
  arctic: {
    id: 'arctic',
    name: 'ARCTIC OUTPOST',
    desc: 'Infiltrate a secret mountain base at night and steal military intel.',
    difficulty: 'Hard',
    playable: true,
    weapons: ['AR7', 'VX'],
    spawn: [0, 0.2, 60],
    spawnYaw: Math.PI,
    ammoCrates: [[3, 0, 54], [-12, 0, -18], [8, 0, -36]],
    objectives: [
      { id: 'approach', title: 'Approach undetected', desc: 'Reach the outer fence', target: [0, 34] },
      { id: 'guards', title: 'Eliminate outer guards', desc: 'Silence the perimeter patrol', target: 'enemies' },
      { id: 'enter', title: 'Enter the base', desc: 'Breach the main gate', target: [0, 20] },
      { id: 'hangar', title: 'Clear the hangar', desc: 'Fight through the vehicle hangar', target: 'enemies' },
      { id: 'data', title: 'Reach the data center', desc: 'Access the server building', target: [0, -45] },
      { id: 'download', title: 'Download intel', desc: 'Hold F at the terminal', target: [0, -45] },
      { id: 'alarm', title: 'Escape the lockdown', desc: 'Alarms are live — run', target: [0, 26] },
      { id: 'exfil', title: 'Reach extraction', desc: 'Get to the evac point', target: [0, 56] },
    ],
  },
  urban: {
    id: 'urban',
    name: 'URBAN BLACKOUT',
    desc: 'Rescue a trapped allied team in a rain-soaked ruined city at night.',
    difficulty: 'Hard',
    playable: true,
    weapons: ['AR7', 'M12'],
    spawn: [0, 0.2, 55],
    spawnYaw: Math.PI,
    ammoCrates: [[-3, 0, 52], [2.5, 0, -30], [10, 8.2, -44]],
    objectives: [
      { id: 'avenue', title: 'Advance up the avenue', desc: 'Push north through the wrecks', target: [0, 24] },
      { id: 'street', title: 'Clear the street', desc: 'Fight between the vehicles', target: 'enemies' },
      { id: 'enter', title: 'Enter the tower', desc: 'Breach the office building', target: [0, -32] },
      { id: 'climb', title: 'Climb the floors', desc: 'Fight up to level 3', target: [0, -38] },
      { id: 'offices', title: 'Clear the offices', desc: 'Eliminate floor hostiles', target: 'enemies' },
      { id: 'rescue', title: 'Find the allied team', desc: 'Reach the trapped squad', target: [8, -46] },
      { id: 'defend', title: 'Defend the position', desc: 'Hold for 90 seconds', target: 'enemies' },
      { id: 'evac', title: 'Evacuate', desc: 'Board the helicopter', target: [0, -20] },
    ],
  },
}
