// Mission definitions: spawn, loadout, sequential objectives.
// Desert Strike is fully playable in Phase A; arctic/urban unlock in Phase B.
export const MISSIONS = {
  desert: {
    id: 'desert',
    name: 'DESERT STRIKE',
    desc: 'Fight through a desert town at sunset and destroy the enemy communications post.',
    difficulty: 'Medium',
    playable: true,
    weapons: ['AR7', 'KX9'],
    spawn: [0, 0.2, 46],
    spawnYaw: Math.PI, // facing -z into town
    objectives: [
      { id: 'enter', title: 'Enter the town', desc: 'Advance through the south gate' },
      { id: 'patrol', title: 'Eliminate the patrol', desc: 'Clear hostiles near the entrance' },
      { id: 'market', title: 'Cross the market', desc: 'Push through the abandoned market' },
      { id: 'roofs', title: 'Clear the rooftops', desc: 'Eliminate rooftop hostiles' },
      { id: 'plaza', title: 'Reach the plaza', desc: 'Advance to the central plaza' },
      { id: 'vehicle', title: 'Destroy the gun truck', desc: 'Blow up the armed vehicle' },
      { id: 'comms', title: 'Reach the comms center', desc: 'Get to the communications building' },
      { id: 'plant', title: 'Plant the explosive', desc: 'Press F at the comms relay' },
      { id: 'escape', title: 'Escape the blast', desc: 'Get clear before detonation' },
    ],
  },
  arctic: {
    id: 'arctic',
    name: 'ARCTIC OUTPOST',
    desc: 'Infiltrate a secret mountain base at night and steal military intel.',
    difficulty: 'Hard',
    playable: true,
    weapons: ['AR7', 'VX'],
    spawn: [0, 0.2, 60],
    spawnYaw: Math.PI,
    objectives: [
      { id: 'approach', title: 'Approach undetected', desc: 'Reach the outer fence' },
      { id: 'guards', title: 'Eliminate outer guards', desc: 'Silence the perimeter patrol' },
      { id: 'enter', title: 'Enter the base', desc: 'Breach the main gate' },
      { id: 'hangar', title: 'Clear the hangar', desc: 'Fight through the vehicle hangar' },
      { id: 'data', title: 'Reach the data center', desc: 'Access the server building' },
      { id: 'download', title: 'Download intel', desc: 'Hold F at the terminal' },
      { id: 'alarm', title: 'Escape the lockdown', desc: 'Alarms are live — run' },
      { id: 'exfil', title: 'Reach extraction', desc: 'Get to the evac point' },
    ],
  },
  urban: {
    id: 'urban',
    name: 'URBAN BLACKOUT',
    desc: 'Rescue a trapped allied team in a rain-soaked ruined city at night.',
    difficulty: 'Hard',
    playable: true,
    weapons: ['AR7', 'M12'],
    spawn: [0, 0.2, 55],
    spawnYaw: Math.PI,
    objectives: [
      { id: 'avenue', title: 'Advance up the avenue', desc: 'Push north through the wrecks' },
      { id: 'street', title: 'Clear the street', desc: 'Fight between the vehicles' },
      { id: 'enter', title: 'Enter the tower', desc: 'Breach the office building' },
      { id: 'climb', title: 'Climb the floors', desc: 'Fight up to level 3' },
      { id: 'offices', title: 'Clear the offices', desc: 'Eliminate floor hostiles' },
      { id: 'rescue', title: 'Find the allied team', desc: 'Reach the trapped squad' },
      { id: 'defend', title: 'Defend the position', desc: 'Hold for 90 seconds' },
      { id: 'evac', title: 'Evacuate', desc: 'Board the helicopter' },
    ],
  },
}
